version: "3"
services:

  postgres:
    container_name: postgres_book
    image: postgres:latest
    ports:
    - "5432:5432"
    volumes:
    # таблицы и их содержимое
    - ./db_data/profile/postgres/:/var/lib/postgresql/data
    - ./db_data/profile/run/postgres.sock:/var/run/postgres/postgres.sock
    env_file:
    - docker.db.env
    networks:
    - postgres_book
  
  pgadmin:
    container_name: pgadmin_book
    image: dpage/pgadmin4
    ports:
    - "8080:80"
    volumes:
    - ./db_data/pgadmin:/root/.pgadmin
    env_file:
    - docker.pgadmin.env
    networks:
    - postgres_book
 

networks:
  postgres_book:
    driver: bridge
